Traceback (most recent call last):
  File "main.py", line 91, in <module>
    main()
  File "main.py", line 82, in main
    set_seed(i)
NameError: name 'i' is not defined
